// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/utils/logger';

// Use environment variables, with fallback for development
// IMPORTANT: In production, always use environment variables!
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://siqmwgeriobtlnkxfeas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcW13Z2VyaW9idGxua3hmZWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTA3MTMsImV4cCI6MjA3MTAyNjcxM30.Wt-9b6ohRw4hpTwT_ewov5sVWmYTFPOFtvxEOZWD8wM";

// Warn in development if using defaults
if (import.meta.env.DEV && (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY)) {
  logger.warn('⚠️ Using default Supabase credentials. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'artrio-auth-token',
    flowType: 'pkce'
  }
});